
build:
  image: docker:20.10.16
  stage: build
  services:
    - name: docker:20.10.16-dind
      command: ["--insecure-registry=gitlab:5050"]
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/my-app:latest .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/my-app:latest