
build:
  image:     
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  stage: build
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "$CI_REGISTRY/$CI_PROJECT_PATH/my-app:latest"
      --insecure-registry "gitlab:5050"
      --skip-tls-verify-registry "gitlab:5050"
